const PAGE_FILES={'/':'pages/home/index.html','/oceano':'pages/oceano/index.html','/zonas':'pages/zonas/index.html','/ecologia':'pages/ecologia/index.html','/ecossistemas':'pages/ecossistemas/index.html','/especies':'pages/especies/index.html','/profundezas':'pages/profundezas/index.html','/cadeia-alimentar':'pages/cadeia-alimentar/index.html','/adaptacoes':'pages/adaptacoes/index.html','/conservacao':'pages/conservacao/index.html','/exploracao':'pages/exploracao/index.html','/jogo':'pages/jogo/index.html','/mapa':'pages/mapa/index.html','/diario':'pages/diario/index.html','/recifes':'pages/recifes/index.html','/glossario':'pages/glossario/index.html','/linha-do-tempo':'pages/linha-do-tempo/index.html','/curiosidades':'pages/curiosidades/index.html','/fontes':'pages/fontes/index.html','/sobre':'pages/sobre/index.html','/desenvolvedores':'pages/desenvolvedores/index.html','/buscar':'pages/buscar/index.html'};
const PAGE_CSS={};Object.keys(PAGE_FILES).forEach(p=>PAGE_CSS[p]=`pages/${p==='/'?'home':p.slice(1)}/style.css`);let activePageStyle=null;
async function loadPageHtml(p){const f=PAGE_FILES[p];if(!f)return null;try{const r=await fetch(f,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}catch(e){console.warn('Falha ao carregar',f,e);return null}}
function loadPageCss(p){if(activePageStyle)activePageStyle.remove();const href=PAGE_CSS[p];if(!href)return;const l=document.createElement('link');l.rel='stylesheet';l.href=href;l.dataset.pageStyle='1';document.head.appendChild(l);activePageStyle=l}
function searchFromHeader(q){q=(q||'').trim();if(q)go('/buscar?q='+encodeURIComponent(q))}
function parseQuery(){const h=location.hash,qi=h.indexOf('?');return qi<0?new URLSearchParams():new URLSearchParams(h.slice(qi+1))}
function fillSearchResults(q){const r=runGlobalSearch(q),el=document.getElementById('results');if(!el)return;el.innerHTML=r.length?r.map((x,i)=>`<article class="card"><span class="index">${String(i+1).padStart(2,'0')}</span><h3>${esc(x[0])}</h3><p>${esc(x[2])}</p><a class="open" href="#${x[1]}">Abrir →</a></article>`).join(''):'<div class="interaction" style="grid-column:1/-1"><h3>Nada encontrado.</h3><p class="subtle">Tente “polvo”, “abissal”, “ecologia”, “tubarão” ou “recifes”.</p></div>'}
function toggleMega(){const m=document.getElementById('mega'),b=document.getElementById('megaBtn'),open=m.classList.toggle('open');if(b){b.setAttribute('aria-expanded',String(open));b.setAttribute('aria-label',open?'Fechar menu':'Abrir menu')}if(open){const f=m.querySelector('a,button');if(f)f.focus()}}
function closeMega(){const m=document.getElementById('mega'),b=document.getElementById('megaBtn');if(m)m.classList.remove('open');if(b){b.setAttribute('aria-expanded','false');b.setAttribute('aria-label','Abrir menu')}}
addEventListener('pointerdown',e=>{const m=document.getElementById('mega');if(!m?.classList.contains('open')||m.contains(e.target)||e.target.closest('#megaBtn'))return;closeMega()});
function toast(m){const t=document.getElementById('toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
async function render(){const p=location.hash.slice(1).split('?')[0]||'/';if(p!=='/jogo'){if(rovFrame)cancelAnimationFrame(rovFrame);rovFrame=null;if(rovState)rovState.running=false;rovState=null}header();let h=null;const dynamic=p.startsWith('/especies/')||(p==='/zonas'&&parseQuery().has('z'))||(p==='/oceano'&&parseQuery().has('bacia'));if(dynamic){if(p.startsWith('/especies/'))h=detail(p.split('/')[2]);else if(p==='/zonas')h=zones();else if(p==='/oceano')h=ocean()}else{h=await loadPageHtml(p);if(!h){if(p==='/')h=home();else if(p==='/oceano')h=ocean();else if(p==='/zonas')h=zones();else if(p==='/ecologia')h=ecologia();else if(p==='/ecossistemas')h=ecossistemas();else if(p==='/especies')h=speciesPage();else if(p==='/profundezas')h=profundezas();else if(p==='/cadeia-alimentar')h=cadeia();else if(p==='/adaptacoes')h=adaptacoes();else if(p==='/conservacao')h=conservation();else if(p==='/exploracao')h=exploracao();else if(p==='/jogo')h=jogo();else if(p==='/mapa')h=mapPage();else if(p==='/diario')h=diario();else if(p==='/recifes')h=recifes();else if(p==='/glossario')h=glossario();else if(p==='/linha-do-tempo')h=timeline();else if(p==='/curiosidades')h=curiosidades();else if(p==='/fontes')h=fontes();else if(p==='/sobre')h=sobre();else if(p==='/buscar')h=searchPage(parseQuery().get('q')||'');else h=notFound()}}document.getElementById('app').innerHTML=layout(h||notFound());loadPageCss(dynamic&&p.startsWith('/especies/')?'/especies':p);document.getElementById('mega').classList.remove('open');const mb=document.getElementById('megaBtn');if(mb)mb.setAttribute('aria-expanded','false');scrollTo({top:0,behavior:'auto'});setMeta(p,p.startsWith('/especies/')&&SPECIES.find(x=>x.id===p.split('/')[2])?[SPECIES.find(x=>x.id===p.split('/')[2]).name,SPECIES.find(x=>x.id===p.split('/')[2]).desc]:null);if(p==='/especies')renderSpecies();if(p==='/glossario')renderGloss();if(p==='/buscar')fillSearchResults(parseQuery().get('q')||'');if(p==='/oceano')initOcean();else initReveal();if(p==='/jogo'){renderPhaseList();resetROVGame();updateFullscreenButton()}applyMode();applyTheme();document.body.dataset.route=p;if(p==='/mapa')hydrateMap();if(p==='/diario')hydrateJournal();const app=document.getElementById('app');if(app&&!firstPaint)app.focus({preventScroll:true});firstPaint=false;updateDepthReadout();applyPhotos();if(typeof registrarPagina==='function'){registrarPagina(p);checkAchievements()}}
let firstPaint=true;addEventListener('hashchange',()=>render().catch(e=>{console.error(e);safeBoot(e)}));let depthTick=false;function updateDepthReadout(){const el=document.documentElement,max=el.scrollHeight-el.clientHeight,s=max?Math.min(1,Math.max(0,el.scrollTop/max)):0,m=Math.round(s*11000);document.getElementById('scrollMeter').style.width=(s*100).toFixed(2)+'%';document.getElementById('headerDepth').textContent=m.toLocaleString('pt-BR')+' m';document.getElementById('depthRailFill').style.height=(s*100).toFixed(2)+'%';document.getElementById('depthRailDot').style.top=(s*100).toFixed(2)+'%';el.style.setProperty('--depth',s.toFixed(3));const zone=m<200?'epipelagica':m<1000?'mesopelagica':m<4000?'batipelagica':m<6000?'abissopelagica':'hadopelagica';document.body.dataset.zone=zone;const hz=document.getElementById('headerZone');if(hz)hz.textContent={epipelagica:'epipelágica',mesopelagica:'mesopelágica',batipelagica:'batipelágica',abissopelagica:'abissopelágica',hadopelagica:'hadopelágica'}[zone]}
addEventListener('scroll',()=>{if(depthTick)return;depthTick=true;requestAnimationFrame(()=>{depthTick=false;updateDepthReadout()})},{passive:true});addEventListener('resize',updateDepthReadout,{passive:true});function safeBoot(){document.getElementById('app').innerHTML='<section class="section" style="padding-top:150px;min-height:70vh"><span class="kicker">ABYSSAL / SISTEMA</span><h1 class="display" style="margin-top:18px">A superfície está sendo restaurada.</h1><p class="lede">Verifique se o projeto foi aberto pelo Live Server.</p></section>'}render().catch(safeBoot);if(typeof marineSnow==='function')marineSnow();
