function detail(id){
  const s=SPECIES.find(x=>x.id===id);
  if(!s)return notFound();
  markSpecies(id);
  const m=meta(s.id);
  return `<section class="pageHero detailHero"><div><nav class="crumbs"><a href="#/">Atlas</a><a href="#/oceano">O oceano</a><a href="#/especies">Espécies</a><span>${esc(s.name)}</span></nav><span class="kicker">${catalogo(s)} · ${esc(s.group)}</span><h1 class="display" style="margin-top:17px;font-size:clamp(3rem,7vw,7rem)">${esc(s.name)}</h1><p style="font-family:Georgia,serif;font-size:1.25rem;color:#8eafb7;font-style:italic">${esc(s.sci)}</p><p class="lede">${esc(s.desc)}</p><div class="heroActions"><a class="btn primary" href="#/especies">← Voltar ao catálogo</a><button class="btn" onclick="addToLog('${s.id}')">Adicionar ao diário</button><button class="btn" onclick="navigator.clipboard?.writeText(location.href);toast('Link da ficha copiado')">Compartilhar ficha</button></div></div><div class="pageArt detailVisual">${photoFrame(s.id,s.name+' — '+s.sci,art(s.type),'big')}</div></section>

<section class="specimenBand">
  <article class="specimenCard">
    <header><span>ESPÉCIME ${catalogo(s).replace('ABY-','')}</span>${statusChip(s.status)}</header>
    <dl>
      <div><dt>Nome</dt><dd>${esc(s.name)}</dd></div>
      <div><dt>Nome científico</dt><dd><em>${esc(s.sci)}</em></dd></div>
      <div><dt>Grupo</dt><dd>${esc(s.group)}</dd></div>
      <div><dt>Habitat</dt><dd>${esc(s.habitat)}</dd></div>
      <div><dt>Profundidade</dt><dd>${esc(s.depth)}</dd></div>
      <div><dt>Tamanho</dt><dd>${esc(s.size)}</dd></div>
      <div><dt>Alimentação</dt><dd>${esc(dietKind(s).join(', '))}</dd></div>
      <div><dt>Ambiente</dt><dd>${esc(m.env||s.habitat)}</dd></div>
    </dl>
    <div class="specimenLinks">
      <a href="#/mapa">Ver no mapa</a>
      <a href="#/ecossistemas">Ver habitat</a>
      <a href="#/zonas${m.z.length?'?z='+(ZONE_META.find(z=>z.key===m.z[0])||{idx:0}).idx:''}">Ver profundidade</a>
      <button onclick="addToLog('${s.id}')">Adicionar ao diário</button>
    </div>
  </article>
  <div class="specimenCol"><h2>Onde vive na coluna d’água</h2>${depthProfile(s.depth,false)||'<p class="subtle">Faixa de profundidade não delimitada nas fontes consultadas.</p>'}</div>
  <div class="specimenCol"><h2>Escala corporal</h2>${sizeScale(s.size)||'<p class="subtle">Tamanho variável entre populações.</p>'}</div>
</section>

${quantBlock(s)}

${modeIs('explorador')&&s.facts&&s.facts[0]?`<section class="section factSpot"><figure><blockquote>${esc(s.facts[0])}</blockquote><figcaption>${esc(s.name)} · <em>${esc(s.sci)}</em></figcaption></figure></section>`:''}

<section class="section detailBody"><div><div class="sectionTitle"><span class="kicker">NOTAS DE CAMPO</span><h2 class="h2">Como essa espécie vive.</h2></div><div class="detailBlocks"><div class="infoBlock"><h3>Alimentação</h3><p>${esc(s.diet)}</p></div><div class="infoBlock"><h3>Comportamento</h3><p>${esc(s.behavior)}</p></div><div class="infoBlock"><h3>Ameaças</h3><p>${s.threats.map(t=>`<span class="pill" style="display:inline-block;margin:2px">${esc(t)}</span>`).join('')}</p></div><div class="infoBlock"><h3>Curiosidades científicas</h3><ul class="factList">${s.facts.map(f=>`<li>${esc(f)}</li>`).join('')}</ul></div></div></div><aside><div class="sourceBox"><span class="kicker">FONTE PRINCIPAL</span><p><a href="${esc(s.source)}" target="_blank" rel="noreferrer">${esc(sourceName(s))}</a></p>${modeIs('cientista')?`<p class="small">${esc(s.source)}</p>`:''}<p class="small">Dados específicos podem variar por população, fonte e método de estimativa. Avaliações de conservação são revisadas periodicamente.</p></div><div class="sourceBox" style="margin-top:12px"><span class="kicker">TAXONOMIA / CONTEXTO</span><p><b>Grupo:</b> ${esc(s.group)}</p><p><b>Habitat:</b> ${esc(s.habitat)}</p><p><b>Bacias:</b> ${m.r.length?m.r.map(r=>esc((REGIONS.find(x=>x.id===r)||{}).name||r)).join(', '):'não indexado'}</p></div></aside></section>

${connectionsBlock(s)}

<section class="section"><div class="sectionTitle"><span class="kicker">PRÓXIMA LEITURA</span><h2 class="h2">Espécies com contexto parecido.</h2><p class="lede">Selecionadas por grupo, faixa de profundidade, ecossistema e bacia em comum.</p></div><div class="grid3">${relatedSpecies(s).map(x=>`<article class="card"><span class="index">${esc(x.group)}</span><h3>${esc(x.name)}</h3><p><em>${esc(x.sci)}</em></p><p class="small">${esc(x.depth)} · ${esc(x.habitat)}</p><a class="open" href="#/especies/${x.id}">Abrir ficha →</a></article>`).join('')}</div></section>

<div class="modeStrip section" style="padding-top:0"><span class="kicker">Modo de leitura</span>${modePanel()}</div>

${flowTrail('especie')}`;
}
function profundezas(){return `<section class="abyss"><div class="abyssIntro"><span class="kicker">09 / PROFUNDEZAS</span><h1 class="display" style="margin-top:15px">ONDE A LUZ NÃO CHEGA.</h1><p class="lede">Desça por uma representação vertical do oceano profundo: pressão aumenta, luz desaparece, alimento fica mais irregular e as soluções biológicas ficam extraordinariamente específicas.</p></div><div class="pressureGauge"><div class="gauge"><div class="fill"></div></div><label><span>PRESSÃO</span><span>~601+ atm</span></label></div><div class="abyssMap">${[['200 m','limiar da zona crepuscular'],['1.000 m','escuridão persistente'],['4.000 m','zona abissopelágica'],['6.000 m','início das condições hadal'],['8.000 m','fossas oceânicas profundas'],['10.900 m','ordem de grandeza do ponto mais profundo conhecido']].map((x,i)=>`<div class="depthMarker" style="top:${i*15+2}%"><span>${x[0]} · ${x[1]}</span></div>`).join('')}<div class="deepLife" style="top:28%">${photoFrame('peixe-pescador','Peixe-pescador-abissal',art('angler'))}<div><small>PEIXE-PESCADOR · emboscada + bioluminescência</small></div></div><div class="deepLife" style="top:52%">${photoFrame('lula-gigante','Lula-gigante',art('squid'))}<div><small>LULA · olhos gigantes + caça em baixa luz</small></div></div><div class="deepLife" style="top:73%">${photoFrame('caranguejo-yeti','Caranguejo-yeti',art('crab'))}<div><small>CARANGUEJO-YETI · fontes hidrotermais</small></div></div></div><div class="abyssCallouts"><div class="callout"><span class="kicker">01</span><h3>Pressão</h3><p class="subtle">A pressão aumenta aproximadamente 1 atmosfera a cada 10 metros de profundidade.</p></div><div class="callout"><span class="kicker">02</span><h3>Energia</h3><p class="subtle">Sem luz, a produtividade local depende de detritos que descem ou de vias químicas em habitats específicos.</p></div><div class="callout"><span class="kicker">03</span><h3>Sentidos</h3><p class="subtle">Bioluminescência, mecanorrecepção e ecolocalização ganham importância quando a visão deixa de ser suficiente.</p></div></div></section>`}
function conservation(){const items=[['Aquecimento','Temperatura altera distribuição, metabolismo e eventos de estresse.'],['Acidificação','A química do carbono dissolvido reduz o pH médio do oceano e afeta organismos calcificadores.'],['Plástico','Resíduos podem interagir com organismos por ingestão, emalhamento e transporte de contaminantes.'],['Pesca incidental','Espécies não alvo podem ser capturadas junto com a espécie-alvo.'],['Habitat','Destruição ou alteração de habitats reduz abrigo, reprodução e alimentação.'],['Biodiversidade','Pressões simultâneas podem simplificar comunidades e reduzir resiliência.']];return `${pageHero('12 / CONSERVAÇÃO','Proteger é entender o sistema.','Conservação marinha combina ecologia, gestão, tecnologia, monitoramento e decisões humanas baseadas em evidência.','turtle','page-conservation')}<section class="section"><div class="grid3">${items.map((x,i)=>`<article class="card"><span class="index">0${i+1}</span><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div></section><section class="section"><div class="grid2"><div><span class="kicker">CAMINHOS</span><h2 class="h2">Soluções trabalham juntas.</h2></div><div class="interaction">${['Áreas marinhas protegidas','Pesca sustentável','Restauração de habitats','Redução de resíduos','Monitoramento científico','Educação ambiental'].map((x,i)=>`<div class="metric"><span>0${i+1}</span><strong>${x}</strong></div>`).join('')}</div></div></section>`}
function exploracao(){return `${pageHero('13 / EXPLORAÇÃO','Como estudar o que não alcançamos.','Mergulhadores, submersíveis, ROVs, AUVs, sonar e sensores ampliam a capacidade de observar o oceano sem depender apenas de acesso humano direto.','angler','page-exploration')}<section class="section"><div class="sectionTitle"><span class="kicker">DO ACESSO AO DADO</span><h2 class="h2">Quando não podemos ir, levamos instrumentos.</h2><p class="lede">Explorar o oceano profundo é uma sequência de decisões: chegar, observar, medir, registrar e transformar sinais em evidência.</p></div><div class="grid3">${[['ROV','Vídeo e instrumentos em tempo real.','OBSERVAR','squid','tech-rov'],['AUV','Rotas autônomas para mapear áreas extensas.','MAPEAR','whale','tech-auv'],['SONAR','Som para enxergar relevo e alvos.','DETECTAR','mola','tech-sonar'],['SUBMERSÍVEL','Acesso tripulado ou especializado.','ACESSAR','angler','tech-sub'],['CTD','Perfil de temperatura, salinidade e profundidade.','MEDIR','jelly','tech-ctd'],['eDNA','Sinais genéticos deixados no ambiente.','INFERIR','octopus','tech-edna']].map((x,i)=>`<article class="card techCard"><div class="techVisual">${photoFrame(x[4],x[0],miniArt(x[3]))}</div><span class="index">0${i+1} / ${x[2]}</span><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div></section><section class="section"><div class="interaction expeditionGateway"><div><span class="kicker">LABORATÓRIO INTERATIVO</span><h2 class="h2" style="font-size:clamp(2.4rem,4.5vw,5rem);margin-top:10px">Desça você mesmo.</h2><p class="lede">Uma missão separada do conteúdo editorial: pilote um ROV, use o sonar, encontre sinais científicos, gerencie energia e volte à superfície com uma leitura completa da expedição.</p></div><div class="expeditionGatewayActions"><div class="missionPreview"><span>01</span><strong>MAPA ABISSAL</strong><small>6 sinais · 3.200 m · retorno</small></div><a class="btn primary" href="#/jogo">Abrir o jogo →</a></div></div></section><section class="section"><div class="grid2"><div><span class="kicker">UM FLUXO DE EXPLORAÇÃO</span><h2 class="h2">Da pergunta à evidência.</h2></div><div class="timeline">${[['01','Pergunta','O que queremos descobrir?'],['02','Acesso','Qual plataforma alcança o local?'],['03','Medição','Que sinais precisam ser registrados?'],['04','Interpretação','Como transformar observações em evidência?']].map(x=>`<div class="event"><div class="year">${x[0]} · ${x[1]}</div><p>${x[2]}</p></div>`).join('')}</div></div></section><section class="section" style="padding-top:20px"><div class="interaction"><div class="eyebrowRow"><div><span class="kicker">CONTINUE A EXPLORAÇÃO</span><h2 class="h2" style="font-size:clamp(2.2rem,4vw,4.5rem);margin-top:10px">Escolha outra lente.</h2></div></div><div style="display:flex;gap:10px;flex-wrap:wrap"><a class="btn primary" href="#/profundezas">Descer às profundezas →</a><a class="btn" href="#/">Voltar para Home</a></div></div></section>`}
function jogo(){const ph=activeMission;return `<section class="gamePageHero"><div class="gameHeroCopy"><span class="kicker">Simulação · pilotagem de ROV</span><h1 class="display" style="margin-top:18px;font-size:clamp(3.2rem,6.4vw,6.6rem)">Seis descidas,<br><span>seis oceanos.</span></h1><p class="lede">Cada fase acontece numa faixa diferente da coluna d\u2019água, com terreno, iluminação, correnteza e perigos próprios. Você começa no recife da plataforma e termina numa fossa hadal a 7.800 m.</p><div class="gameLegend"><span>WASD ou setas · mover</span><span>Shift · impulso</span><span>Espaço · pulso de sonar</span><span>F · tela cheia</span><span>P · pausar</span></div><div class="gameBrief"><div class="step"><b>Desça</b><span>O sonar só responde abaixo da cota indicada em cada fase.</span></div><div class="step"><b>Colete</b><span>Com o eco ativo, aproxime-se do alvo antes de o pulso se apagar.</span></div><div class="step"><b>Volte</b><span>Dados só contam se o ROV for extraído acima da cota de retorno.</span></div></div></div><div class="gameHeroVisual"><div class="rovHeroArt"><div class="rovEye"></div><div class="rovLight left"></div><div class="rovLight right"></div><div class="rovArm one"></div><div class="rovArm two"></div></div><div class="heroDepthRuler"><span>0 m</span><span>1 km</span><span>4 km</span><span>7,8 km</span></div></div></section>

<section class="section phaseSection"><div class="sectionTitle"><span class="kicker">Progressão</span><h2 class="h2">Escolha a fase.</h2><p class="lede">Cada fase é liberada ao concluir a anterior. O progresso fica salvo neste navegador.</p></div><div class="phaseList" id="phaseList"></div></section>

<section class="section gameStageSection"><div class="gameShell" id="rovGame"><div class="gameHeader"><div><span class="small">Operação abismo · cartografia científica</span><strong id="gameMission">${esc(ph.id)} · ${esc(ph.name)}</strong><small id="missionSubtitle" class="phaseSub">${esc(ph.zone)} · ${esc(ph.depthLabel)}</small></div><div class="gameHeaderRight"><div class="gameReadout"><span>Profundidade <b id="gameDepth">0 m</b></span><span>Amostras <b id="gameData">0 / ${ph.samples.length}</b></span><span>Energia <b id="gameEnergy">${ph.energy}%</b></span><span>Tempo <b id="gameTime">00:00</b></span></div><div class="gameHeaderBtns"><button class="btn gameBtn" id="gameFullscreenBtn" onclick="toggleGameFullscreen()">Tela cheia</button><button class="btn primary gameBtn" id="gameStart" onclick="startROVGame()">Iniciar descida</button></div></div></div><div class="gameMain"><div class="canvasFrame"><canvas id="rovCanvas" width="1200" height="670" aria-label="Simulador de ROV"></canvas><div class="sonarFlash" id="sonarFlash"></div><div class="gameOverlay" id="gameHint"><div class="overlayIcon">◈</div><strong>${esc(ph.id)} · ${esc(ph.name)}</strong><span>${esc(ph.brief)}</span></div></div><aside class="gamePanel"><div class="panelTitle"><span class="kicker">Controle de missão</span><h3>Console do ROV</h3></div><div class="barBlock"><div><span>Energia</span><b id="energyText">${ph.energy}%</b></div><div class="energyBar"><i id="energyFill"></i></div></div><div class="barBlock"><div><span>Zona</span><b id="zoneText">Epipelágica</b></div><div class="zoneBar"><i id="zoneFill"></i></div></div><div class="sensorCard"><span class="small">Sonar</span><strong id="sonarStatus">Bloqueado</strong><p id="sonarText">O sonar só responde abaixo de ${ph.sonarDepth.toLocaleString('pt-BR')} m.</p><p class="pulseLine">Pulsos: <b id="pulsesLeft">${ph.pulses>50?'livre':ph.pulses+' restantes'}</b></p></div><div class="samples" id="sampleList"></div><div class="missionSteps" id="missionSteps"><div class="missionStep active"><i>1</i><div><b>Descer</b><span id="missionStep1Text">Chegue à cota do sonar.</span></div></div><div class="missionStep"><i>2</i><div><b>Coletar</b><span id="missionStep2Text">Recupere as amostras.</span></div></div><div class="missionStep"><i>3</i><div><b>Retornar</b><span id="missionStep3Text">Suba até a cota de extração.</span></div></div></div><div class="panelHint"><span class="small">Objetivo</span><p id="missionText">${esc(ph.brief)}</p></div></aside></div><div class="gameFooter"><div class="gameState" id="gameState">Sistema · pronto para iniciar</div><div class="gameFooterActions"><button class="btn" onclick="resetROVGame()">Reiniciar fase</button><button class="btn primary" id="gameFinishBtn" onclick="finishROV(true)" disabled>Extrair ROV</button></div></div></div><p class="phaseLesson" id="phaseLesson">${esc(ph.lesson)}</p></section>

<section class="section"><div class="grid3"><article class="card"><span class="index">Energia</span><h3>A bateria é o relógio.</h3><p>Impulso gasta mais que o dobro do deslocamento normal, e bater no terreno também custa carga. Parar recupera um pouco.</p></article><article class="card"><span class="index">Sonar</span><h3>Nem tudo está visível.</h3><p>Abaixo da zona iluminada o campo visual encolhe. O eco do sonar é a única forma de localizar as amostras — e nas fases profundas ele é contado.</p></article><article class="card"><span class="index">Retorno</span><h3>Dado que não volta não existe.</h3><p>Chegar ao fundo não encerra nada. A missão só conta quando o veículo é extraído acima da cota de retorno.</p></article></div></section>`}
function cadeia(){return `${pageHero('10 / ECOLOGIA','Energia em rede.','A cadeia simplificada ajuda a começar; na natureza, relações alimentares formam redes, com múltiplas presas, predadores e caminhos de reciclagem.','mola','page-food')}<section class="section"><div class="interaction"><div class="timeline">${[['Fitoplâncton','Produtores. Capturam energia luminosa e introduzem matéria orgânica em muitas teias marinhas.'],['Zooplâncton','Consumidores primários; transferem energia do micro para organismos maiores.'],['Peixes pequenos','Podem conectar plâncton a predadores maiores.'],['Peixes grandes','Ocupam diferentes posições tróficas conforme espécie e idade.'],['Predadores de topo','Podem reorganizar comportamento e abundância de presas.'],['Decompositores','Reciclam matéria e devolvem nutrientes aos ciclos biogeoquímicos.']].map((x,i)=>`<div class="event"><div class="year">0${i+1} / ${x[0].toUpperCase()}</div><h3>${x[0]}</h3><p>${x[1]}</p></div>`).join('')}</div></div></section>`}
function adaptacoes(){return `${pageHero('11 / ADAPTAÇÕES','Viver no mar é negociar com a física.','Camuflagem, bioluminescência, osmorregulação, ecolocalização e tolerância à pressão são respostas a problemas ambientais específicos.','octopus','page-adapt')}<section class="section"><div class="grid3">${[['Camuflagem','Reduz detecção por predadores ou presas.','Polvo'],['Mimetismo','Aproxima aparência de outro organismo ou do ambiente.','diversas linhagens'],['Bioluminescência','Produção biológica de luz com várias funções.','peixes abissais'],['Ecolocalização','Usa som e ecos para orientar e localizar alvos.','cetáceos'],['Osmorregulação','Mantém água e sais em equilíbrio interno.','peixes ósseos'],['Tolerância à pressão','Estruturas e moléculas precisam funcionar sob grande pressão.','fauna profunda']].map((x,i)=>`<article class="card"><span class="index">0${i+1}</span><h3>${x[0]}</h3><p>${x[1]}</p><small>${x[2]}</small></article>`).join('')}</div></section>`}
function recifes(){return `${pageHero('14 / RECIFES','Arquitetura viva.','Corais são animais; recifes são ecossistemas. Luz, temperatura, química, herbivoria e relações simbióticas determinam sua dinâmica.','reef','eco-reef')}<section class="section"><div class="grid2"><div class="interaction">${photoFrame('eco-reef','Recife de coral',art('reef'))}<p class="small">ILUSTRAÇÃO CONCEITUAL · COLÔNIA DE CORAL</p></div><div><span class="kicker">SIMBIOSE</span><h2 class="h2">Coral + simbiontes + ambiente.</h2><p class="lede">Muitos corais construtores de recife mantêm relações com dinoflagelados simbióticos. Quando o ambiente ultrapassa tolerâncias fisiológicas, pode ocorrer branqueamento.</p></div></div></section><section class="section"><div class="grid3">${['Biodiversidade','Proteção costeira','Turismo e cultura'].map((x,i)=>`<article class="card"><span class="index">0${i+1}</span><h3>${x}</h3><p>${['Abrigos e recursos criam oportunidades para muitas formas de vida.','Estruturas recifais reduzem energia de ondas em diversos contextos.','Recifes também têm importância econômica, cultural e educacional.'][i]}</p></article>`).join('')}</div></section>`}
function glossario(){return `${pageHero('15 / GLOSSÁRIO','Palavras para navegar o oceano.','Um glossário compacto para consultar termos recorrentes na biologia e oceanografia marinhas.','jelly','page-zones')}<section class="section"><label class="searchBox" style="display:block;max-width:700px"><span class="kicker">BUSCAR TERMO</span><input id="glossQuery" oninput="renderGloss()" placeholder="abissal, bentônico, pelágico..."></label><div id="glossGrid" class="gloss" style="margin-top:30px"></div></section>`}
function renderGloss(){const q=(document.getElementById('glossQuery')?.value||'').toLowerCase();const arr=GLOSS.filter(x=>(x[0]+' '+x[1]).toLowerCase().includes(q));document.getElementById('glossGrid').innerHTML=arr.map((x,i)=>`<article><span class="small">0${i+1}</span><b>${x[0]}</b><p>${x[1]}</p></article>`).join('')||'<div class="interaction" style="grid-column:1/-1">Termo não encontrado.</div>'}
function timeline(){return `${pageHero('16 / LINHA DO TEMPO','Oceanos em perspectiva profunda.','Uma narrativa resumida sobre grandes etapas da história da Terra, da vida marinha e da exploração humana.','whale','page-timeline')}<section class="section"><div class="timeline">${[['~4,4 bilhões de anos','Os primeiros oceanos surgem em uma Terra muito diferente da atual.'],['~3,5 bilhões de anos','Registros mais antigos de vida preservada apontam para um planeta já biologicamente ativo.'],['~541 milhões de anos','A Explosão Cambriana marca uma diversificação importante da vida animal no registro fóssil.'],['Era Mesozoica','Diversas linhagens marinhas se diversificam, incluindo grandes répteis marinhos e novos peixes.'],['Cenozoico','Mamíferos marinhos, incluindo cetáceos, passam por grandes mudanças evolutivas.'],['Era moderna','Submersíveis, satélites, sensores e veículos autônomos ampliam a observação dos oceanos.']].map((x,i)=>`<div class="event"><div class="year">${x[0]}</div><h3>${x[0]}</h3><p>${x[1]}</p></div>`).join('')}</div></section>`}
function curiosidades(){return `${pageHero('17 / CURIOSIDADES','Pequenas perguntas. Grandes oceanos.','Perguntas rápidas para abrir portas de investigação sem transformar ciência em espetáculo vazio.','narwhal','page-curiosities')}<section class="section"><div class="grid3">${[['Qual é o maior animal?','A baleia-azul é o maior animal conhecido da Terra.'],['Como os animais produzem luz?','Por bioluminescência, usando processos químicos ou relações com organismos luminosos.'],['Por que o oceano parece azul?','A luz é absorvida e espalhada de maneira diferente conforme o comprimento de onda e as propriedades da água.'],['Qual é o papel do zooplâncton?','Consumir produtores e transferir matéria para níveis tróficos superiores, além de participar de fluxos biogeoquímicos.'],['O que há no fundo?','Sedimentos, rochas, organismos bentônicos, detritos e habitats químicos extremos em alguns locais.'],['Por que a migração importa?','Ela conecta habitats, redistribui nutrientes e permite acompanhar recursos sazonais.']].map((x,i)=>`<article class="card"><span class="index">0${i+1}</span><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div></section>`}
function fontes(){return `${pageHero('18 / FONTES','A ciência por trás da experiência.','Instituições e bases de referência para aprofundar dados e conferir informações específicas.','octopus','page-ecology')}<section class="section"><div class="interaction">${SOURCES.map((x,i)=>`<a href="${x[1]}" target="_blank" rel="noreferrer" style="display:grid;grid-template-columns:50px 1fr 20px;gap:15px;align-items:center;padding:20px 0;border-bottom:1px solid var(--line);text-decoration:none"><span class="small">0${i+1}</span><div><strong>${x[0]}</strong><div class="small">${x[1]}</div></div><b style="color:var(--cyan)">↗</b></a>`).join('')}</div></section>`}
function sobre(){return `${pageHero('19 / SOBRE','Observar. Medir. Interpretar. Comunicar.','Biologia marinha é um campo que combina trabalho de campo, laboratório, modelagem, conservação, tecnologia e comunicação científica.','seahorse','page-about')}<section class="section"><div class="grid2"><div><span class="kicker">ABYSSAL</span><h2 class="h2">Um guia pensado para curiosidade com contexto.</h2></div><div><p class="lede">O projeto organiza temas de oceanografia e biologia marinha em uma experiência de navegação que lembra um atlas de campo: cada página cria uma lente diferente, mas todas compartilham a mesma linguagem visual.</p><p class="subtle">As páginas usam ilustrações vetoriais originais para evitar dependência de imagens externas sem licença. Os links nas fontes permitem aprofundamento.</p></div></div></section>`}
function notFound(){return `<section class="section" style="padding-top:160px"><span class="kicker">404 / DERIVA OCEÂNICA</span><h1 class="display" style="margin-top:15px">Essa rota afundou.</h1><p class="lede">A página não foi encontrada.</p><a class="btn primary" href="#/">Voltar à superfície</a></section>`}
function generic(path){return pageHero('ABYSSAL',path,'Conteúdo em construção.','jelly')}
function searchPage(q=''){return `<section class="section" style="padding-top:130px"><span class="kicker">BUSCA GLOBAL</span><h1 class="display" style="font-size:clamp(3rem,6vw,7rem);margin-top:15px">${q?`Resultados para “${esc(q)}”`:'Pesquisar'}</h1><label class="searchBox" style="display:block;max-width:700px;margin-top:30px"><span class="kicker">TERMO</span><input id="globalSearch" value="${esc(q)}" onkeydown="if(event.key==='Enter')searchFromHeader(this.value)" placeholder="espécie, ecologia, profundidade..."></label><div id="results" class="grid3" style="margin-top:35px"></div></section>`}
function runGlobalSearch(q){const ql=slug(q);const pages=[['Ecologia marinha','/ecologia','Relações ecológicas, fluxo de energia, produtividade e conectividade.'],['Ecossistemas','/ecossistemas','Recifes, manguezais, kelp, mar aberto, estuários e mais.'],['Profundezas','/profundezas','Pressão, bioluminescência, escuridão e vida abissal.'],['Teias alimentares','/cadeia-alimentar','Fitoplâncton, zooplâncton, peixes e predadores.'],['Adaptações','/adaptacoes','Camuflagem, ecolocalização, osmorregulação e pressão.'],['Conservação','/conservacao','Aquecimento, acidificação, plástico, pesca e soluções.']];const results=[...pages.filter(x=>slug(x.join(' ')).includes(ql)),...SPECIES.filter(s=>slug([s.name,s.sci,s.group,s.habitat,s.desc,s.depth,s.status].join(' ')).includes(ql)).map(s=>[s.name,'/especies/'+s.id,s.sci])];return results}
function searchFromHeader(q){q=(q||'').trim();if(!q)return;go('/buscar?q='+encodeURIComponent(q))}
function parseQuery(){const h=location.hash;const qi=h.indexOf('?');if(qi<0)return new URLSearchParams();return new URLSearchParams(h.slice(qi+1))}
function buscar(){const q=parseQuery().get('q')||'';const html=searchPage(q);setTimeout(()=>{const r=runGlobalSearch(q);const el=document.getElementById('results');if(el)el.innerHTML=r.length?r.map((x,i)=>`<article class="card"><span class="index">${String(i+1).padStart(2,'0')}</span><h3>${esc(x[0])}</h3><p>${esc(x[2])}</p><a class="open" href="#${x[1]}">Abrir →</a></article>`).join(''):'<div class="interaction" style="grid-column:1/-1"><h3>Nada encontrado.</h3><p class="subtle">Tente “polvo”, “abissal”, “ecologia”, “tubarão” ou “recifes”.</p></div>'},0);return html}
function toggleMega(){const m=document.getElementById('mega'),b=document.getElementById('megaBtn');const open=m.classList.toggle('open');if(b){b.setAttribute('aria-expanded',open?'true':'false');b.setAttribute('aria-label',open?'Fechar menu':'Abrir menu')}if(open){const f=m.querySelector('a,button');if(f)f.focus()}}
function closeMega(){const m=document.getElementById('mega'),b=document.getElementById('megaBtn');if(m)m.classList.remove('open');if(b){b.setAttribute('aria-expanded','false');b.setAttribute('aria-label','Abrir menu');b.focus()}}
addEventListener('pointerdown',e=>{const m=document.getElementById('mega');if(!m||!m.classList.contains('open'))return;if(m.contains(e.target)||e.target.closest('#megaBtn'))return;m.classList.remove('open');const b=document.getElementById('megaBtn');if(b)b.setAttribute('aria-expanded','false')});
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
