function diario(){const log=getLog(), speciesCount=log.species.length, missionCount=log.missions.length;const recent=[...log.missions].reverse().slice(0,6);return `<section class="logPage"><div class="logHero"><div><span class="kicker">ABYSSAL / DIÁRIO DE BORDO</span><h1 class="display" style="margin-top:16px;font-size:clamp(3.2rem,7vw,7rem)">SUAS<br>DESCOBERTAS.</h1><p class="lede">O atlas guarda seu progresso localmente neste navegador: espécies consultadas, regiões visitadas e missões concluídas.</p>${modePanel()}</div><div class="discoveryCard"><span class="discoveryCode">${dailyDiscovery().type}</span><h3>${dailyDiscovery().title}</h3><p class="subtle">${dailyDiscovery().text}</p><div class="discoveryMeta"><span class="pill">${dailyDiscovery().depth}</span><span class="pill">DESCOBERTA DO DIA</span></div></div></div><div class="atlasStats"><div class="atlasStat"><strong>${speciesCount}</strong><span>espécies vistas</span></div><div class="atlasStat"><strong>${missionCount}</strong><span>missões concluídas</span></div><div class="atlasStat"><strong>${log.map.length}</strong><span>regiões visitadas</span></div><div class="atlasStat"><strong>${log.discoveries||0}</strong><span>descobertas</span></div></div><div class="logGrid"><div class="interaction"><span class="kicker">REGISTRO</span><h2 class="h2" style="font-size:clamp(2.2rem,4vw,4rem);margin-top:8px">Últimas missões.</h2>${recent.length?recent.map((m,i)=>`<div class="logEntry"><b>${m}</b><span>Expedição concluída e salva no diário local.</span></div>`).join(''):'<p class="subtle">Ainda não há missões concluídas. Abra o jogo para começar sua primeira expedição.</p>'}<a class="btn primary" href="#/jogo">Ir para o jogo →</a></div><div class="interaction"><span class="kicker">DISTINTIVOS</span><h2 class="h2" style="font-size:clamp(2.2rem,4vw,4rem);margin-top:8px">Marcas de campo.</h2><div class="badgeGrid"><div class="badge"><strong>${missionCount>=1?'✓':'○'} Primeira expedição</strong><small>Conclua uma missão.</small></div><div class="badge"><strong>${speciesCount>=3?'✓':'○'} Naturalista</strong><small>Visite 3 espécies.</small></div><div class="badge"><strong>${log.map.length>=3?'✓':'○'} Cartógrafo</strong><small>Visite 3 regiões.</small></div><div class="badge"><strong>${missionCount>=6?'✓':'○'} Operação completa</strong><small>Conclua as 6 missões.</small></div></div></div></div><section class="section" style="padding:70px 0 0"><div class="interaction"><span class="kicker">CENTRAL DE EXPLORAÇÃO</span><h2 class="h2" style="font-size:clamp(2.4rem,4.5vw,5rem);margin-top:8px">Onde você quer investigar?</h2><div class="commandLinks"><a class="commandLink" href="#/mapa"><b>Mapa oceânico</b><span>Escolha uma região para continuar.</span></a><a class="commandLink" href="#/especies"><b>Espécies</b><span>Abra fichas e construa sua coleção.</span></a><a class="commandLink" href="#/jogo"><b>Missões</b><span>Entre na próxima expedição.</span></a></div></div></section></section>`}
const TITLES={'/':['Guia de campo marinho','Atlas de biologia marinha: zonas de profundidade, espécies, ecologia e conservação.'],'/oceano':['O oceano','Salinidade, circulação, temperatura e pressão em um planeta majoritariamente coberto por água.'],'/zonas':['Zonas de profundidade','Da epipelágica à hadopelágica: como luz, pressão e alimento mudam com a profundidade.'],'/especies':['Enciclopédia de espécies','Fichas de espécies marinhas com habitat, profundidade, dieta, comportamento e conservação.'],'/profundezas':['Criaturas das profundezas','Bioluminescência, pressão e escuridão: adaptações da vida abissal.'],'/ecologia':['Ecologia marinha','Fluxo de energia, produtividade e conectividade nos ecossistemas do mar.'],'/ecossistemas':['Ecossistemas marinhos','Recifes, manguezais, kelp, estuários, mar aberto e fontes hidrotermais.'],'/adaptacoes':['Adaptações','Camuflagem, ecolocalização, osmorregulação e tolerância à pressão.'],'/cadeia-alimentar':['Teias alimentares','Do fitoplâncton aos predadores de topo.'],'/conservacao':['Conservação marinha','Aquecimento, acidificação, plástico e pesca — e o que funciona.'],'/exploracao':['Exploração científica','ROVs, AUVs, sonar e submersíveis.'],'/jogo':['Simulador de ROV','Pilote um veículo remoto e colete amostras na coluna d\u2019água.'],'/mapa':['Mapa das bacias','Atlântico, Pacífico, Índico, Ártico e Antártico.'],'/diario':['Diário de bordo','Seu registro de espécies, missões e regiões visitadas.'],'/recifes':['Recifes de coral','Estrutura, simbiose e branqueamento.'],'/glossario':['Glossário','Termos de oceanografia e biologia marinha.'],'/linha-do-tempo':['Linha do tempo','Marcos da exploração oceanográfica.'],'/curiosidades':['Notas de campo','Fatos verificáveis sobre o oceano.'],'/fontes':['Fontes','Instituições e referências usadas neste atlas.'],'/sobre':['Sobre o ABYSSAL','O que é este atlas e para quem foi feito.'],'/buscar':['Busca','Pesquise espécies, temas e zonas.']};
function setMeta(path,extra){const t=TITLES[path];let title,desc;if(extra){title=extra[0];desc=extra[1]}else if(t){title=t[0];desc=t[1]}else{title='Página não encontrada';desc='Este endereço não existe no atlas.'}document.title=(path==='/'?'ABYSSAL — '+title:title+' — ABYSSAL');const m=document.querySelector('meta[name="description"]');if(m)m.setAttribute('content',desc)}
function header(){const cur=location.hash.slice(1).split('?')[0]||'/';document.getElementById('mainNav').innerHTML=NAV.map(([n,u])=>`<a href="#${u}"${u===cur?' aria-current="page"':''}>${n}</a>`).join('')}
function layout(content){return content}
function hydrateJournal(){
  const log=getLog(), d=dailyDiscovery();
  const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v};
  set('journalSpeciesCount',log.species.length);set('journalMissionCount',log.missions.length);set('journalMapCount',log.map.length);set('journalDiscoveryCount',log.discoveries||0);
  const dc=document.getElementById('journalDiscovery');if(dc){dc.querySelector('.discoveryCode').textContent=d.type;dc.querySelector('h3').textContent=d.title;const p=dc.querySelector('p');if(p)p.textContent=d.text;const pill=dc.querySelector('.pill');if(pill)pill.textContent=d.depth}
  const recent=document.getElementById('journalRecent');if(recent)recent.innerHTML=log.missions.length?[...log.missions].reverse().slice(0,6).map(m=>`<div class="logEntry"><b>${esc(m)}</b><span>Expedição concluída e salva no diário local.</span></div>`).join(''):'<p class="subtle">Ainda não há missões concluídas. Abra o jogo para começar sua primeira expedição.</p>';
  const badges=document.getElementById('journalBadges');if(badges){const ok=[log.missions.length>=1,log.species.length>=3,log.map.length>=3,log.missions.length>=6];badges.querySelectorAll('.badge strong').forEach((el,i)=>el.textContent=(ok[i]?'✓ ':'○ ')+['Primeira expedição','Naturalista','Cartógrafo','Operação completa'][i])}
}
